image: python:3.7-slim-stretch

stages:
  - test

before_script:
  - apt-get update && apt-get -y install sudo make curl git && pip3 install cookiecutter
  - sh prepare_template.sh
  - cd reforis-example-plugin

test:
  stage: test
  script:
    - make test

lint:
  stage: test
  script:
    - make lint

init-langs:
  stage: test
  script:
    - make init-langs

test-build:
  stage: test
  script:
    - make build-js
