image: python:3.7-slim-stretch

stages:
  - test

before_script:
  - apt-get update && apt-get -y install sudo make curl git && pip3 install cookiecutter
  - cookiecutter --no-input .
  - cd reforis-example-plugin
  - make prepare-dev

test:
  stage: test
  script:
    - make test

lint:
  stage: test
  script:
    - make lint

translate:
  stage: test
  script:
    - make init-langs
